#spring:
#  ai:
#    openai:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      api-key: sk-80e4e6e0b5f747f5af996c811d6c6a58
#      chat:
#        options:
#          model: qwen-plus
#          temperature: 0.7
#      embedding:
#        options:
#          model: text-embedding-v4
#    vectorstore:
#      milvus:
#        client:
#          host: "localhost"
#          port: 19530
#          username: "root"
#          password: "milvus"
#        databaseName: "default"
#        collectionName: "vector_store1"
#        initialize-schema: true
#        embeddingDimension: 1024
#        indexType: IVF_FLAT
#        metricType: COSINE

#spring:
#  ai:
#    openai:
#      base-url: https://ark-cn-beijing.bytedance.net/api/v3
#      api-key: d91db9bf-169a-4de8-a3cd-8f23c017018d
#      chat:
#        options:
#          model: ep-20260225121255-9bn2l
#          temperature: 0.7


spring:
  ai:
    openai:
      base-url: https://api.kxaug.xyz/
      api-key: sk-BcSlK5LUOuzMJjiKwDI4catb16MlRa5at3mwAbEopSEHf0iI
      chat:
        options:
          model: gpt-5.4
          temperature: 0.7
#    embedding:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      api-key: sk-80e4e6e0b5f747f5af996c811d6c6a58
#      options:
#        model: text-embedding-v4
#    vectorstore:
#      milvus:
#        client:
#          host: "localhost"
#          port: 19530
#          username: "root"
#          password: "milvus"
#        databaseName: "default"
#        collectionName: "vector_store_gpt"
#        initialize-schema: true
#        embeddingDimension: 1024
#        indexType: IVF_FLAT
#        metricType: COSINE
logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.ai: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
---
spring:
  datasource:
    url: jdbc:h2:file:./data/ai_chat;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
